channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=4.1.2
  - matplotlib=3.8.3
  - numpy=1.26.4
  - pandas=2.2.1
  - openai=1.13.1
  - librosa=0.10.0
  - click=8.1.3
  - fuzzywuzzy=0.18.0
  - pydub=0.25.1
  - tqdm=4.66.2
  - lxml=5.1.0
  - dash=2.16.0
  - tiktoken=0.6.0
  - pip:
    - OpenCC
    - noisereduce
    - fake_useragent

